if (APPLE)
  execute_process(COMMAND sysctl -n hw.logicalcpu OUTPUT_VARIABLE NPROC)
elseif (${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
  # When CMake 3.25 is mandated, we can use elseif(LINUX)
  execute_process(COMMAND nproc OUTPUT_VARIABLE NPROC)
endif()
